name: linting, testing, building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    strategy:
      matrix:
        node-version: [18.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install modules
        run: pnpm i --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Linting typescript
        run: pnpm run eslint

      - name: Linting css
        run: pnpm run stylelint

      - name: Unit testing
        run: pnpm run test:unit

      - name: Build storybook
        run: pnpm run storybook:build

      - name: Screenshots testing
        run: pnpm run test:screenshots:ci
